Revert "added springframework to pom.xml"
This reverts commit 06d7d58f51ab63f5ca18480e4922c6a5463ade98.

There were various issues with netty wanting to allocate unsafe buffers and access epoll.

Exception in thread "main" java.lang.NoClassDefFoundError: reactor/util/retry/Retry
at com.couchbase.client.core.config.DefaultConfigurationProvider.lambda$loadAndRefreshGlobalConfig$15(DefaultConfigurationProvider.java:346)

Suppressed: java.lang.UnsatisfiedLinkError: no com_couchbase_client_core_deps_netty_transport_native_epoll_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)

16:36:30.195 [main] DEBUG com.couchbase.client.core.deps.io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class com.couchbase.client.core.deps.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @365185bd

16:36:30.274 [main] DEBUG com.couchbase.client.core.deps.io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'com_couchbase_client_core_deps_netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no com_couchbase_client_core_deps_netty_transport_native_epoll_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)

30.180 [main] DEBUG com.couchbase.client.core.deps.io.netty.util.internal.PlatformDependent0 - Java version: 14
16:36:30.182 [main] DEBUG com.couchbase.client.core.deps.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
16:36:30.184 [main] DEBUG com.couchbase.client.core.deps.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
16:36:30.185 [main] DEBUG com.couchbase.client.core.deps.io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
16:36:30.191 [main] DEBUG com.couchbase.client.core.deps.io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
   at com.couchbase.client.core.deps.io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)